### ISSUE TITLE
MCreator not loading in plugin

### ISSUE THREAD

**Issue by YoItSoul** [Pylo/MCreatorGenerator-Forge-1.12.2#12]
**Describe the bug**
MCreator will not accept either installation routes for `mcreator-generator-1.12.2-2020.4-v2.2.1`.

**To Reproduce**
Download `mcreator-generator-1.12.2-2020.4-v2.2.1` from [https://mcreator.net/system/files/2020-09/mcreator-generator-1.12.2-2020.5-v2.3.0.zip](url) and try to installing plugin via MCreator, or by placing the plugin into the MCreator workspace plugins folder.

Nothing is printed to console.

**Details**
 - OS: [Windows]
 - MCreator version [2020.4]
 - Generator type: 1.12.2-2020.4-v2.2.1

**Demo workspace**
Cannot be attached, as the plugin never actually is able to be used or is successfully loaded into the MCreator workspace.

**Additional context**
`mcreator-generator-1.12.2-2020.4-v2.2.1.zip`, the previous 1.12.2 generator version can be successfully loaded but has an outdated version of forge, therefore causing dependencies with other mods to be unusable.

**Comment by KlemenDEV** [comment]
mcreator-generator-1.12.2-2020.5-v2.3.0.zip - as the filename suggests, this generator is for MCreator 2020.5, not 2020.4.
For 2020.4 use 2020.4 version of generator.
