### ISSUE TITLE
"When bullet hits block" trigger prefers the west side of a block.

### ISSUE THREAD

**Issue by Gun-Man** [Pylo/MCreatorGenerator-Forge-1.12.2#15]
When using the "When bullet hits block" trigger, it will only run the given procedure if the projectile hits the west side of the block .

When using the "When bullet hits block" trigger, it will only run the given procedure if the projectile hits the block's face that's facing west, but only if you check what block the projectile hit (checking if the projectile hit grass block for example).

Steps To Reproduce
Install the 1.12.2 mod generator plugin, make a new project, make a ranged item, set it up as you like, when at the trigger section add a procedure for "When bullet hits block", then program the following, If - get block at x y z = (block you want to shoot, grass block for example) Do - (what you want to do, say "Hello World!" in the player's action bar for example, save it, run the client, shoot the block that you want to shoot on all sides, you will find that it only dose what you want it to do when the projectile hits the block's west facing face.
![image](https://user-images.githubusercontent.com/72329248/95024570-c9a3b980-0651-11eb-8f3e-381734d800fe.png)

Details

MCreator version: 2020.4
Generator type: forge-1.12.2
OS: Windows 10
Example Workspace.
[Example.Mod.1.12.2.generater.plugin.requiered.zip](https://github.com/MCreator/Generator-Forge-1.12.2/files/5324114/Example.Mod.1.12.2.generater.plugin.requiered.zip)

Logs both debug and normal.
[debug.log](https://github.com/MCreator/Generator-Forge-1.12.2/files/5324115/debug.log)
[latest.log](https://github.com/MCreator/Generator-Forge-1.12.2/files/5324116/latest.log)

Note: Again, sorry for posting this issue in the main MCreator issue tracker.

**Comment by Defeatomizer** [comment]
All files seem to be generated correctly.
Try reproducing this bug in other MCreator versions. If problem remains, then it's unfortunately MC 1.12.2 bug and is not to be fixed since MC 1.13-1.16 are already released. :confused:

**Comment by KlemenDEV** [comment]
This is most likely how MC detects arrow collisions. Seems like inGround triggers in west side: https://github.com/MCreator/Generator-Forge-1.12.2/blob/8af5be8b6ab696baedda6638d5221f6f997a1d71/forge-1.12.2/templates/rangeditem.java.ftl#L214

There is not much that can be changed about this from our side.

**Comment by Defeatomizer** [comment]
>This is most likely how MC detects arrow collisions.

I checked EntityArrow class in 1.12 source code and I just don't understand the reason it triggers on west-side only.

But I still hope there are some workarounds.
