### ISSUE TITLE
Forge version out of date

### ISSUE THREAD

**Issue by AzazelMango** [Pylo/MCreatorGenerator-Forge-1.12.2#16]
Where would I change the forge version used in this plugin, if possible?

EDIT:
I eventually got it to run but I had to override the forge version check for one of the mods.
I think that know how to update forge would be a good thing to have. If at all possible.

**Comment by KlemenDEV** [comment]
Changing version could introduce bugs. Feel free to fork and alter https://github.com/MCreator/Generator-Forge-1.12.2/blob/2020.5/forge-1.12.2/generator.yaml. But make sure to respect the license.
