### ISSUE TITLE
Mod doesn't working

### ISSUE THREAD

**Issue by aquafoxwolf** [Pylo/MCreatorGenerator-Forge-1.12.2#17]
When im trying to open minecraft it says "This mod is for 1.13 and newer versions" or something like this

**Details**
 - OS: windows 10
 - MCreator version 2020.5
 - Generator type: forge-1.12.2

**Comment by aquafoxwolf** [comment]
Why its invalid?
I made mod and when im trying to use it minecraft says this mod is for 1.13 or newer version, im using 1.12.2 generator

**Comment by KlemenDEV** [comment]
Include crash logs and screenshots..

**Comment by aquafoxwolf** [comment]
![Zrzut ekranu (85)](https://user-images.githubusercontent.com/65615229/96001324-31b78400-0e38-11eb-8eba-171e2496cfb4.png)
[latest.log](https://github.com/MCreator/Generator-Forge-1.12.2/files/5378730/latest.log)
@KlemenDEV

**Comment by KlemenDEV** [comment]
Is ManyNewMaterialsMod.jar rudy mod? Otherwise the problem is with your rudy mod

**Comment by aquafoxwolf** [comment]
yes it is

**Comment by KlemenDEV** [comment]
Attach jar

**Comment by aquafoxwolf** [comment]
github says we dont support that file type

**Comment by aquafoxwolf** [comment]
[Uploading ManyNewMaterialsMod.zip…]()

**Comment by aquafoxwolf** [comment]
it works with zip

**Comment by aquafoxwolf** [comment]
@KlemenDEV

**Comment by aquafoxwolf** [comment]
ok i fixed it, if someone have same problem delete every mcreator folder from your pc then it will start working
