### ISSUE TITLE
On player right-click (and probably other hand-based clicks) cause double-firing procedures

### ISSUE THREAD

**Issue by AechtRob** [Pylo/MCreatorGenerator-Forge-1.12.2#18]
The onRightClickBlock method/trigger fires twice when constructed via the builder screens. It appears to fire from both hands.

To solve, we need this kind of thing in the trigger code:

```
@SubscribeEvent
	public void onRightClickBlock(PlayerInteractEvent.RightClickBlock event) {
		EntityPlayer entity = event.getEntityPlayer();
		if (event.getHand() != entity.getActiveHand())
			return;

[do blah blah blah here]
```

etc.....

**Comment by KlemenDEV** [comment]
Provide a PR and we can get this into the next release ;)

**Comment by AechtRob** [comment]
I don't know how to do that - I just know what the code needs to look like - sorry.

**Comment by KinyoshiMods** [comment]
> Provide a PR and we can get this into the next release ;)

I also don't know how to do that or what a PR is.. a pull request?

**Comment by KlemenDEV** [comment]
Correct
