### ISSUE TITLE
Crafting Recipes not giving XP

### ISSUE THREAD

**Issue by KinyoshiMods** [Pylo/MCreatorGenerator-Forge-1.12.2#20]
Crafting recipes do not give XP when crafting them items (however, the furnace smelting XP works fine)

 - MCreator version 2020.5 latest pre-release (at time of posting)
 - Generator type: forge-1.12.2 (2020.5-v2.3.1)

I was going to make a dummy workspace with one recipe, but it would take someone longer to load that than just to make a blank workspace and/or load up their 1.12.2 mod and test :D

**Comment by KlemenDEV** [comment]
Crafting recipes do not support this, more here: https://minecraft.gamepedia.com/Recipe
