### ISSUE TITLE
Missing air blocks.

### ISSUE THREAD

**Issue by Fandalf89** [Pylo/MCreatorGenerator-Forge-1.12.2#21]
**Describe the bug**
Two types of block are missing (Block.VOID_AIR and Block.CAVE_AIR). I'm been trying to create some new blocks but when I create Generation Procedures there's always missing these two block types, the Block.AIR is still there but the other two aren't.

**Details**
 - OS: Windows 10
 - MCreator version 2020.5
 - Generator type: forge-1.12.2

**Comment by KlemenDEV** [comment]
![image](https://user-images.githubusercontent.com/16374228/100515986-c6740800-3180-11eb-96be-e3176cca6d54.png)
