### ISSUE TITLE
2021.1 compatibility

### ISSUE THREAD

**Issue by KlemenDEV** [Pylo/MCreatorGenerator-Forge-1.12.2#22]
Future placeholder

**Comment by LexShadow** [comment]
Any news for this is it's going to happen? and will you be able not to show the options not supported so we know what will work or not.

**Comment by Fisheiyy** [comment]
smelting recipes are broken in only 2021.1 snapshot, editing the .mcreator file and changing the version to below 2020.5 so I can open it in 2020.5 shows no broken recipes
![image](https://user-images.githubusercontent.com/54205282/113807872-7a3a6500-972a-11eb-9d1b-01e83b06082a.png)

**Comment by KlemenDEV** [comment]
This issue is still in work and plugin is not compatible yet
