### ISSUE TITLE
Fence Gate Issue

### ISSUE THREAD

**Issue by ToasterBox834** [Pylo/MCreatorGenerator-Forge-1.12.2#25]
Describe the bug
I made a wood pack with a custom green wood called Flinchwood and after 1-10 minutes I started getting a compiling error pop-up menu where it tells me that there is an error with the fence gate and I cannot fix it or even figure out what's causing this error. I have a .zip file of the workspace for people to help me figure out what's causing the error. If you can find out what's causing this please tell me.

p.s ty Pylo for this amazing application!
[fistful-o-weapons1.zip](https://github.com/MCreator/Generator-Forge-1.12.2/files/5785238/fistful-o-weapons1.zip)

Details

MCreator version: 2020.5
Generator type: forge-1.12.2
OS: Windows

**Comment by ToasterBox834** [comment]
I put this in the MCreator repository and they said to put it here

**Comment by Esquader** [comment]
Oh I see no one responded while we have the same error
