### ISSUE TITLE
Gui

### ISSUE THREAD

**Issue by ghost** [Pylo/MCreatorGenerator-Forge-1.12.2#26]
I have do a Gui for ask player to be married I have also create a item, weedingrin with texture and all work, but when I have link the gui in the item, go to the world for try the gui is litteraly not open I can do what I wan't that do nothing :/
![image](https://user-images.githubusercontent.com/77652599/104981376-c8cc4300-5a08-11eb-9ea3-b27d99fa323b.png)
my Gui 
![image](https://user-images.githubusercontent.com/77652599/104981398-d5e93200-5a08-11eb-84a0-d55290db34aa.png)

also :
Version of MCreator 2020.5
Forge 1.12.2

**Comment by KlemenDEV** [comment]
1.12.2 requires you to define open GUI manually
