### ISSUE TITLE
GUI Texture does not appear in Minecraft

### ISSUE THREAD

**Issue by HKS-HNS** [Pylo/MCreatorGenerator-Forge-1.12.2#28]
**Describe the bug**
When i open the gui then the texture disappear only if i have no slots.

**Screenshots**
In MCreator:
https://user-images.githubusercontent.com/59665579/105808090-6c889680-5fa7-11eb-8c07-bb6066f03943.png
In Game:
https://user-images.githubusercontent.com/59665579/105808199-993cae00-5fa7-11eb-89a9-b3b6fc65be3a.png

**Details**
 - OS: Windows 10
 - MCreator version 2020.5
 - Generator type: forge-1.12.2

**Comment by MagmaMCNet** [comment]
yea i have no idea why so if you add gui with inventory it will work
