### ISSUE TITLE
Geckolib compatibility

### ISSUE THREAD

**Issue by Fandalf89** [Pylo/MCreatorGenerator-Forge-1.12.2#29]
So as we all know Geckolib Plugin is available for Mcreator now, and since you still want update the generator for the most recent versions of Mcreator I have a suggestion. Gecko is still releasing Geckolib for 1.12.2, so I thought that can be added Geckolib compatibility for the Generator_1.12.2.

**Comment by KlemenDEV** [comment]
This is up to geckolib plugin, not 1.12.2 generator.
