### ISSUE TITLE
Tags Don't Accept Capitol Letters

### ISSUE THREAD

**Issue by Moonspire** [Pylo/MCreatorGenerator-Forge-1.12.2#33]
**Describe the bug**
When trying to add tags in a crafting recipe, the editor refuses to accept tags with capitol letters. This is an issue as almost all tags from other mods are structured like so: ingotCopper. So when trying to make a recipe accept any copper tagged with ingotCopper you have to put it in as ingotcopper then lock the recipe code and change the case to capitol.

**To Reproduce**
Create a recipe with a tag with a capitol letter

**Details**
 - OS: Windows 10
 - MCreator version: 2020.5
 - Generator type: forge-1.12.2

**Additional context**
Could also be present when creating tags, unsure though since I haven't made a tag since starting using this plugin

**Comment by Moonspire** [comment]
Issue is indeed present when creating tags as well

**Comment by SNikolaBogdanic** [comment]
I also share this same problem with even the same details of the software shared by Moonspire, but at a worse scale: I cannot even edit the code of the tag as well.

Please, we need a solution.
