### ISSUE TITLE
Gui Image Condition

### ISSUE THREAD

**Issue by SpiDrone** [Pylo/MCreatorGenerator-Forge-1.12.2#34]
**Describe the bug**
Within the Gui, you are meant to be able to apply a condition to determine whether or the image is visible.  However even thought it accepts my procedure, which I have confirmed works in MCreator (without the plugin) the image displays regardless of conditions.

**Details**
 - OS: Windows
 - MCreator version 2020.5
 - Generator type: forge-1.12.2

1.12 generator not working->
[SharableWorkspace.zip](https://github.com/MCreator/Generator-Forge-1.12.2/files/5969227/SharableWorkspace.zip)

1.15 version that works ->
[SharableWorkspace2.zip](https://github.com/MCreator/Generator-Forge-1.12.2/files/5969240/SharableWorkspace2.zip)

**Comment by SpiDrone** [comment]
I forgot to mention I have the R and G buttons set aside to open the gui, and change the value.  so you can see that the image will toggle on and off on 1.15, but not with the 1.12 generator

**Comment by OlivadThefighter** [comment]
I may have something like this?
I tried to make a guidebook but the pictures won't show up

**Comment by KlemenDEV** [comment]
I don't think conditions are supported in the 1.12.2 generator so this is the reason for this.
