### ISSUE TITLE
Entity Models (.java) doesn't work

### ISSUE THREAD

**Issue by Byllfighter** [Pylo/MCreatorGenerator-Forge-1.12.2#35]
I want bakport my mod The Void (link:https://mcreator.net/modification/70440/void), but .java models doesnt words. I try to export .java for 1.12.2, but it doesn't work. 
`
 Error:
Executing 
    Gradle task: build

Build 
    info: MCreator 2021.1.03117 EAP (03117), forge-1.12.2, 64-bit, 7966 MB, 
    Windows 8.1, JVM 1.8.0_275, JAVA_HOME: E:\Pylo\MCreatorEAP20211b03117\jdk

This 
    mapping 'snapshot_20171003' was designed for MC 1.12! Use at your own 
    peril.

:deobfCompileDummyTask

:deobfProvidedDummyTask

:sourceApiJava 
    UP-TO-DATE

:compileApiJava 
    NO-SOURCE

:processApiResources 
    NO-SOURCE

:apiClasses 
    UP-TO-DATE

:sourceMainJava 
    UP-TO-DATE

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityCodeLaser.java:201: 
    error: cannot find symbol 
 
      public static class Modellaser extends EntityModel<Entity> {

 
                                             ^

 
     symbol:   class EntityModel

 
     location: class EntityCodeLaser

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityCodeLaser.java:214: 
    error: cannot find symbol 
 
         public void render(MatrixStack matrixStack, IVertexBuilder buffer, 
    int packedLight, int packedOverlay, float red, float green, float blue,

 
                            ^

 
     symbol:   class MatrixStack

 
     location: class Modellaser

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityCodeLaser.java:214: 
    error: cannot find symbol 
 
         public void render(MatrixStack matrixStack, IVertexBuilder buffer, 
    int packedLight, int packedOverlay, float red, float green, float blue,

 
                                                     ^

 
     symbol:   class IVertexBuilder

 
     location: class Modellaser

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityPortalTheCube.java:174: 
    error: cannot find symbol 
 
      public static class Modelplate extends EntityModel<Entity> {

 
                                             ^

 
     symbol:   class EntityModel

 
     location: class EntityPortalTheCube

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityPortalTheCube.java:185: 
    error: cannot find symbol 
 
         public void render(MatrixStack matrixStack, IVertexBuilder buffer, 
    int packedLight, int packedOverlay, float red, float green, float blue,

 
                            ^

 
     symbol:   class MatrixStack

 
     location: class Modelplate

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityPortalTheCube.java:185: 
    error: cannot find symbol 
 
         public void render(MatrixStack matrixStack, IVertexBuilder buffer, 
    int packedLight, int packedOverlay, float red, float green, float blue,

 
                                                     ^

 
     symbol:   class IVertexBuilder

 
     location: class Modelplate

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityPortalUp.java:172: 
    error: cannot find symbol 
 
      public static class Modelplate extends EntityModel<Entity> {

 
                                             ^

 
     symbol:   class EntityModel

 
     location: class EntityPortalUp

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityPortalUp.java:183: 
    error: cannot find symbol 
 
         public void render(MatrixStack matrixStack, IVertexBuilder buffer, 
    int packedLight, int packedOverlay, float red, float green, float blue,

 
                            ^

 
     symbol:   class MatrixStack

 
     location: class Modelplate

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityPortalUp.java:183: 
    error: cannot find symbol 
 
         public void render(MatrixStack matrixStack, IVertexBuilder buffer, 
    int packedLight, int packedOverlay, float red, float green, float blue,

 
                                                     ^

 
     symbol:   class IVertexBuilder

 
     location: class Modelplate

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityTheCube.java:220: 
    error: cannot find symbol 
 
      public static class Modelcubeboss extends EntityModel<Entity> {

 
                                                ^

 
     symbol:   class EntityModel

 
     location: class EntityTheCube

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityTheCube.java:232: 
    error: cannot find symbol 
 
         public void render(MatrixStack matrixStack, IVertexBuilder buffer, 
    int packedLight, int packedOverlay, float red, float green, float blue,

 
                            ^

 
     symbol:   class MatrixStack

 
     location: class Modelcubeboss

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityTheCube.java:232: 
    error: cannot find symbol 
 
         public void render(MatrixStack matrixStack, IVertexBuilder buffer, 
    int packedLight, int packedOverlay, float red, float green, float blue,

 
                                                     ^

 
     symbol:   class IVertexBuilder

 
     location: class Modelcubeboss

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityTVWalker.java:169: 
    error: cannot find symbol 
 
      public static class Modelvoidwalker extends EntityModel<Entity> {

 
                                                  ^

 
     symbol:   class EntityModel

 
     location: class EntityTVWalker

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityTVWalker.java:246: 
    error: cannot find symbol 
 
         public void render(MatrixStack matrixStack, IVertexBuilder buffer, 
    int packedLight, int packedOverlay, float red, float green, float blue,

 
                            ^

 
     symbol:   class MatrixStack

 
     location: class Modelvoidwalker

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityTVWalker.java:246: 
    error: cannot find symbol 
 
         public void render(MatrixStack matrixStack, IVertexBuilder buffer, 
    int packedLight, int packedOverlay, float red, float green, float blue,

 
                                                     ^

 
     symbol:   class IVertexBuilder

 
     location: class Modelvoidwalker

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityVoidWalker.java:167: 
    error: cannot find symbol 
 
      public static class Modelvoidwalker extends EntityModel<Entity> {

 
                                                  ^

 
     symbol:   class EntityModel

 
     location: class EntityVoidWalker

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityVoidWalker.java:244: 
    error: cannot find symbol 
 
         public void render(MatrixStack matrixStack, IVertexBuilder buffer, 
    int packedLight, int packedOverlay, float red, float green, float blue,

 
                            ^

 
     symbol:   class MatrixStack

 
     location: class Modelvoidwalker

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityVoidWalker.java:244: 
    error: cannot find symbol 
 
         public void render(MatrixStack matrixStack, IVertexBuilder buffer, 
    int packedLight, int packedOverlay, float red, float green, float blue,

 
                                                     ^

 
     symbol:   class IVertexBuilder

 
     location: class Modelvoidwalker

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityVoidWarden.java:200: 
    error: cannot find symbol 
 
      public static class Modelvoidwarden extends EntityModel<Entity> {

 
                                                  ^

 
     symbol:   class EntityModel

 
     location: class EntityVoidWarden

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityVoidWarden.java:237: 
    error: cannot find symbol 
 
         public void render(MatrixStack matrixStack, IVertexBuilder buffer, 
    int packedLight, int packedOverlay, float red, float green, float blue,

 
                            ^

 
     symbol:   class MatrixStack

 
     location: class Modelvoidwarden

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityVoidWarden.java:237: 
    error: cannot find symbol 
 
         public void render(MatrixStack matrixStack, IVertexBuilder buffer, 
    int packedLight, int packedOverlay, float red, float green, float blue,

 
                                                     ^

 
     symbol:   class IVertexBuilder

 
     location: class Modelvoidwarden

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityVoidWardenMob.java:165: 
    error: cannot find symbol 
 
      public static class Modelvoidwarden extends EntityModel<Entity> {

 
                                                  ^

 
     symbol:   class EntityModel

 
     location: class EntityVoidWardenMob

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityVoidWardenMob.java:202: 
    error: cannot find symbol 
 
         public void render(MatrixStack matrixStack, IVertexBuilder buffer, 
    int packedLight, int packedOverlay, float red, float green, float blue,

 
                            ^

 
     symbol:   class MatrixStack

 
     location: class Modelvoidwarden

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityVoidWardenMob.java:202: 
    error: cannot find symbol 
 
         public void render(MatrixStack matrixStack, IVertexBuilder buffer, 
    int packedLight, int packedOverlay, float red, float green, float blue,

 
                                                     ^

 
     symbol:   class IVertexBuilder

 
     location: class Modelvoidwarden

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityVoidWatcher.java:178: 
    error: cannot find symbol 
 
      public static class Modelvoidwatcher extends EntityModel<Entity> {

 
                                                   ^

 
     symbol:   class EntityModel

 
     location: class EntityVoidWatcher

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityVoidWatcher.java:192: 
    error: cannot find symbol 
 
         public void render(MatrixStack matrixStack, IVertexBuilder buffer, 
    int packedLight, int packedOverlay, float red, float green, float blue,

 
                            ^

 
     symbol:   class MatrixStack

 
     location: class Modelvoidwatcher

E:\Pylo\Workspaces\1.16.4\thevoid1122\build\sources\main\java\net\bullfighter\thevoidmod\entity\EntityVoidWatcher.java:192: 
    error: cannot find symbol 
 
         public void render(MatrixStack matrixStack, IVertexBuilder buffer, 
    int packedLight, int packedOverlay, float red, float green, float blue,

 
                                                     ^

 
     symbol:   class IVertexBuilder

 
     location: class Modelvoidwatcher

27 
    errors

:compileJava 
    FAILED

FAILURE: 
    Build failed with an exception.

* 
    What went wrong:

Execution 
    failed for task ':compileJava'.

> 
    Compilation failed; see the compiler error output for details.

* 
    Try:

Run 
    with --stacktrace option to get the stack trace. Run with --info or 
    --debug option to get more log output. Run with --scan to get full 
    insights.

* 
    Get more help at https://help.gradle.org

BUILD 
    FAILED in 10s

5 
    actionable tasks: 3 executed, 2 up-to-date

BUILD 
    FAILED

Task 
    completed in 19 seconds

Mcreator version: 2021.1 b03117

**Comment by KlemenDEV** [comment]
1.15.2 model in 1.12.2 won't work
