### ISSUE TITLE
Feature request: FE support

### ISSUE THREAD

**Issue by marralesfios** [Pylo/MCreatorGenerator-Forge-1.12.2#37]
**Describe the bug**
It says
WARNING: Block block_energy_receive is not supported by the selected generator. It will be skipped.
when I tried to use "send energy to  block".
**Details**
 - OS: Windows
 - MCreator version 2021.5 EAP 03117
 - Generator type: forge-1.12.2

**Comment by KlemenDEV** [comment]
Duplicate: https://github.com/MCreator/Generator-Forge-1.12.2/issues/32
