### ISSUE TITLE
[Question] Is this actually supported

### ISSUE THREAD

**Issue by CrispyChips6660** [Pylo/MCreatorGenerator-Forge-1.12.2#4]
You stated that this generator isn't supported yet there is an issue and feature request template...
I am confused XD

**Comment by KlemenDEV** [comment]
Did you check it?

> As this generator is no longer supported, feature requests most likely won't be added.
> 
> To get the feature into this generator, open a pull request with the feature implemented instead.

I added issues so bug reports can be still reported and potentially fixed by a community. Another thing to see the OSS readiness of MCreator.
