### ISSUE TITLE
bug for door and fencegate 

### ISSUE THREAD

**Issue by cbaie9** [Pylo/MCreatorGenerator-Forge-1.12.2#40]
**Describe the bug**
the fencegate and the door are bugged

**fencegate**
- can't build properly
**door**
can't be in game there is a models + texture bug
![2021-04-22_11 05 00](https://user-images.githubusercontent.com/75169332/115687867-e20fc300-a35a-11eb-9cc2-9f1081b389a3.png)

**elements in the workspace**
![](https://cdn.discordapp.com/attachments/830109067816075314/834714826977968148/unknown.png)
**gradle**
![](https://cdn.discordapp.com/attachments/830109067816075314/834715433641967636/unknown.png)
**fencegate file**
![](https://cdn.discordapp.com/attachments/830109067816075314/834715255208411156/unknown.png)

**Details**
 - OS: [e.g. Windows]
 - MCreator version [e.g. 2020.5]
 - Generator type: forge-1.12.2

**Demo workspace**
If the bug is related to the workspace, always provide a minimal reproducible example workspace, export it to a shareable ZIP file, and attach it to the ticket.

[bug_report1.12.zip](https://github.com/MCreator/Generator-Forge-1.12.2/files/6356983/bug_report1.12.zip)

i'm french sorry for the bad english

**Comment by KlemenDEV** [comment]
These block bases are not supported in 1.12.2 generator.
