### ISSUE TITLE
Procedure block [ Add {x} {y} to {z} inventory ] weird behavior

### ISSUE THREAD

**Issue by zsvan** [Pylo/MCreatorGenerator-Forge-1.12.2#48]
**Describe the bug**
I had a simple procedure - if you click with a tool on a plant, plant is cut and player gets **random number** of either **item1** or **item2**. Procedure used:
![image](https://user-images.githubusercontent.com/17712352/117555912-a0259300-b063-11eb-8333-dcc7a2fa3ec0.png)

But it behaved in a _very_ weird way - sometimes you got **both** items, and sometimes **items got removed**. Example on the clip:
https://streamable.com/k6pcxf

**To Reproduce**
I think simply using the procedure block [ Add {x} {y} to {z} inventory ] and a simple [ if: random(0,1); do ] will be enough.
I've made sure the math result isn't giving me a negative number so it's not that.

**Details**
 - OS: W10
 - MCreator version 2021.1 16710
 - Generator type: forge-1.12.2

**Comment by zsvan** [comment]
Oh by the way - if I use this instead:
![image](https://user-images.githubusercontent.com/17712352/117555976-60ab7680-b064-11eb-9b31-187cb13dc6c8.png)
it seems to spawn items properly, option A or option B, without doubling the items

**Comment by MysteriousWolf** [comment]
To me, this sounds like a synchronization issue with random numbers. Try to add a "server-side check" to your procedure like in this wiki post: https://mcreator.net/wiki/developing-multiplayer-compatible-mods
