### ISSUE TITLE
New Procedure Blocks for Vanilla Functions do not Work with 1.12.2

### ISSUE THREAD

**Issue by TechTastic** [Pylo/MCreatorGenerator-Forge-1.12.2#50]
I don't mean using newer potion effects or newer mobs. I mean blocks like Tame [] by [] and Make [] ride [] that should be able to work in 1.12.2 but don't and just get skipped instead.

I haven't stumbled across any other problems yet as I only recently opened the 1.12 generator again to make a small mod for my own personal use but I am sure there are other blocks representing basic vanilla functions that are unusable.

And yes my mod and modpack need to be in 1.12.2 because of other mods I plan to use such as Valkyrien Skies

**Comment by MysteriousWolf** [comment]
Unless someone ports the procedure blocks to other versions, they don't work by default as different versions can have different implementations.
