### ISSUE TITLE
when switching from 2020.5 to 2021.1, the bounding boxes of the models increase

### ISSUE THREAD

**Issue by Trotsky1940** [Pylo/MCreatorGenerator-Forge-1.12.2#51]
**Describe the bug**
when I start switching from version 2020.5 to 2021.1, all the hitboxes of the models increase
**Details**
 - OS: Windows 10
 - MCreator version 2020.5 and 2021.1
 - Generator type: forge-1.12.2

![2021-08-15_13 30 42](https://user-images.githubusercontent.com/78540442/129475735-55f22619-a388-43c6-b4f7-dc0f5c45a65a.png)
![063b895dd97b](https://user-images.githubusercontent.com/78540442/129475741-91a07fe4-0243-4ca0-813c-1e72f8305bbc.png)
[2021.1.zip](https://github.com/MCreator/Generator-Forge-1.12.2/files/6987997/2021.1.zip)
[2020.5.zip](https://github.com/MCreator/Generator-Forge-1.12.2/files/6987998/2020.5.zip)

**Comment by fisk1234ost** [comment]
Caused by MCreator not this plugin

**Comment by MysteriousWolf** [comment]
I believe this is caused by different Minecraft versions calculating bounding boxes differently and could be fixed in the generator. While there is no official support on it, anyone is welcome to pick it up and fix it themselves.
