### ISSUE TITLE
Why can't I use variables?

### ISSUE THREAD

**Issue by 3284987829** [Pylo/MCreatorGenerator-Forge-1.12.2#52]
As soon as uses the variable to report the error, is the plug-in question?

**Comment by MysteriousWolf** [comment]
IIRC 1.12.2 generator never supported variables in the first place, so someone would need to contribute and add variable support for it to work.

**Comment by 3284987829** [comment]
ok

**Comment by 3284987829** [comment]
But I can't write code.
