### ISSUE TITLE
The plugin is not visible neither in the plugin manager neither the generator

### ISSUE THREAD

**Issue by noobio3** [Pylo/MCreatorGenerator-Forge-1.12.2#55]
**Bug**
i can't see it inside the forge generator neither in the plugin manger

I exported the folder inside plugins folder and put zip file in there too

**Details**
 - OS: Windows 8.1
 - MCreator 2021.2
 - Generator type: forge-1.12.2

**Additional context**
if i am doing something wrong can someone explain it to me?

**Comment by MysteriousWolf** [comment]
Are you sure you installed it correctly? Have you followed [this guide](https://mcreator.net/wiki/developing-mcreator-plugins#wiki-index-6)? Where did you download the plugin from?

**Comment by MagmaMCNet** [comment]
not working for mcreator 2021.2 yet

**Comment by MysteriousWolf** [comment]
> 
> 
> not working for mcreator 2021.2 yet

This is indeed the correct answer, I missed the MCreator version part. It's not and will not be supported unless someone picks this plugin up and does them themselves.
