### ISSUE TITLE
I'm working on a update but..

### ISSUE THREAD

**Issue by TheDUFFY1** [Pylo/MCreatorGenerator-Forge-1.12.2#59]
I need a hand. I have fixed a few stupid bugs like the bounding boxes being broken, that was an easy one. I am also working on adding Enchantments to the Generator but I am a bit stuck. I need code from a 1.12 forge-added enchantment to reference. I have used the enchantment code from a newer Generator as reference, re-written it with the correct strings, the code appears to be formatted correctly, it compiles without error and the game launches. But the enchantment simple cannot be found in the game. If I can find a working example of a simple enchantment made to work in a forge version for 1.12.x I should be able to identify the problem with my code, I have found 2 examples on the internet that are too convoluted to help. Forge does not appear to support modding 1.12 anymore so I can't seem to find anything there.

I will be porting the Generator to the latest version of MCreator eventually. I had a go at porting it and kind of just lost motivation as it will require me to reverse engineer the newest generators and there is a lot to fix for some reason, anything to do with a procedure interacting with a block in anyway just breaks, but I'm happy fixing the current version for now. So I am adding Enchantments as a way of learning how it all works.

The situation put simply, I have done some of Java coding in the past but nothing like this, I have had to reverse engineer all the Generators in order for me to find string references, work out its structure and simply how it works. I am close to adding Enchantments, but I need help from you guys to find it, as I am doing this in my spare time after work, I don't have a lot of time.

Another thing I will need is some info on using Github, I cannot figure it out. I don't know where I should have posted this, nor do I have any idea on how I would publish my changes to the code when I am ready. Any help at all will be appreciated.

**Comment by MCAlexisYT** [comment]
It's quite sad, because I want to backport the 2 new music discs (Pigstep from 1.16 and otherside from 1.18) to 1.12 and my only way to do it is gone...

**Comment by RewynEbonpelt** [comment]
I recommend maybe checking out the enchantments in the Ice and Fire mod, if you haven't already.
