### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by Lorange7** [Pylo/MCreatorGenerator-Forge-1.12.2#69]
ive put the zip in the plug ins folder (i checked the install help page to see what to do, it tells you how to make a plugin not install it)
and it doesnt show up only 1.16 and 1.18

![mcreator1 12 2clip1](https://user-images.githubusercontent.com/75991265/193467954-511ff445-f2f2-4ac8-9161-9b5a8077808f.PNG)
![mcreator1 12 2clip2](https://user-images.githubusercontent.com/75991265/193467958-8a33bad8-0f10-41e9-9dc7-817a073208b1.PNG)

**Comment by MysteriousWolf** [comment]
This generator only works for MCreator versions up to 2021.1 (https://github.com/MCreator/Generator-Forge-1.12.2#for-mcreator-20211).
