### ISSUE TITLE
"Can use ranged item" procedure doesn't work properly.

### ISSUE THREAD

**Issue by FallenSeverlay** [Pylo/MCreatorGenerator-Forge-1.12.2#9]
**Describe the bug**
"Can use ranged item" procedure doesn't work properly. If you make this procedure "Return: false" your ranged item will create projectile anyway.

**To Reproduce**
Just create "Ranged Item" and add "Can use ranged item" procedure. And then just make this procedure "Return: false".

**Details**
 - OS: Windows
 - MCreator version 2020.4
 - Generator type: forge-1.12.2

**Additional context**
This bug does not appear if you are using [forge-1.15.2] version

**Comment by KlemenDEV** [comment]
Ranged items in 1.12.2 do not have condition support. If you want to get it added, I suggest you open a pull request with this feature, 1.12.2 gen is no longer maintained.
